// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/v1/policy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Scenario         string                 `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Risk             int32                  `protobuf:"varint,2,opt,name=risk,proto3" json:"risk,omitempty"` // 0-5 scale
	LatencyBudgetMs  float64                `protobuf:"fixed64,3,opt,name=latency_budget_ms,json=latencyBudgetMs,proto3" json:"latency_budget_ms,omitempty"`
	RamKb            int64                  `protobuf:"varint,4,opt,name=ram_kb,json=ramKb,proto3" json:"ram_kb,omitempty"`
	PeerAlgorithms   []string               `protobuf:"bytes,5,rep,name=peer_algorithms,json=peerAlgorithms,proto3" json:"peer_algorithms,omitempty"`
	KeyRotationHours int32                  `protobuf:"varint,6,opt,name=key_rotation_hours,json=keyRotationHours,proto3" json:"key_rotation_hours,omitempty"`
	CertValidityDays int32                  `protobuf:"varint,7,opt,name=cert_validity_days,json=certValidityDays,proto3" json:"cert_validity_days,omitempty"`
	ExecuteCrypto    bool                   `protobuf:"varint,8,opt,name=execute_crypto,json=executeCrypto,proto3" json:"execute_crypto,omitempty"` // if true, perform actual KEM math
	Region           string                 `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	DeviceType       string                 `protobuf:"bytes,10,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_api_proto_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *ContextRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *ContextRequest) GetRisk() int32 {
	if x != nil {
		return x.Risk
	}
	return 0
}

func (x *ContextRequest) GetLatencyBudgetMs() float64 {
	if x != nil {
		return x.LatencyBudgetMs
	}
	return 0
}

func (x *ContextRequest) GetRamKb() int64 {
	if x != nil {
		return x.RamKb
	}
	return 0
}

func (x *ContextRequest) GetPeerAlgorithms() []string {
	if x != nil {
		return x.PeerAlgorithms
	}
	return nil
}

func (x *ContextRequest) GetKeyRotationHours() int32 {
	if x != nil {
		return x.KeyRotationHours
	}
	return 0
}

func (x *ContextRequest) GetCertValidityDays() int32 {
	if x != nil {
		return x.CertValidityDays
	}
	return 0
}

func (x *ContextRequest) GetExecuteCrypto() bool {
	if x != nil {
		return x.ExecuteCrypto
	}
	return false
}

func (x *ContextRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ContextRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

type AlgorithmConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kem           string                 `protobuf:"bytes,1,opt,name=kem,proto3" json:"kem,omitempty"`
	Sig           string                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	HybridPeer    string                 `protobuf:"bytes,3,opt,name=hybrid_peer,json=hybridPeer,proto3" json:"hybrid_peer,omitempty"`
	SecurityLevel int32                  `protobuf:"varint,4,opt,name=security_level,json=securityLevel,proto3" json:"security_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmConfig) Reset() {
	*x = AlgorithmConfig{}
	mi := &file_api_proto_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmConfig) ProtoMessage() {}

func (x *AlgorithmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmConfig.ProtoReflect.Descriptor instead.
func (*AlgorithmConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *AlgorithmConfig) GetKem() string {
	if x != nil {
		return x.Kem
	}
	return ""
}

func (x *AlgorithmConfig) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

func (x *AlgorithmConfig) GetHybridPeer() string {
	if x != nil {
		return x.HybridPeer
	}
	return ""
}

func (x *AlgorithmConfig) GetSecurityLevel() int32 {
	if x != nil {
		return x.SecurityLevel
	}
	return 0
}

var File_api_proto_v1_policy_proto protoreflect.FileDescriptor

const file_api_proto_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/policy.proto\x12\fpqcengine.v1\"\xe8\x02\n" +
	"\x0eContextRequest\x12\x1a\n" +
	"\bscenario\x18\x01 \x01(\tR\bscenario\x12\x12\n" +
	"\x04risk\x18\x02 \x01(\x05R\x04risk\x12*\n" +
	"\x11latency_budget_ms\x18\x03 \x01(\x01R\x0flatencyBudgetMs\x12\x15\n" +
	"\x06ram_kb\x18\x04 \x01(\x03R\x05ramKb\x12'\n" +
	"\x0fpeer_algorithms\x18\x05 \x03(\tR\x0epeerAlgorithms\x12,\n" +
	"\x12key_rotation_hours\x18\x06 \x01(\x05R\x10keyRotationHours\x12,\n" +
	"\x12cert_validity_days\x18\a \x01(\x05R\x10certValidityDays\x12%\n" +
	"\x0eexecute_crypto\x18\b \x01(\bR\rexecuteCrypto\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12\x1f\n" +
	"\vdevice_type\x18\n" +
	" \x01(\tR\n" +
	"deviceType\"}\n" +
	"\x0fAlgorithmConfig\x12\x10\n" +
	"\x03kem\x18\x01 \x01(\tR\x03kem\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\tR\x03sig\x12\x1f\n" +
	"\vhybrid_peer\x18\x03 \x01(\tR\n" +
	"hybridPeer\x12%\n" +
	"\x0esecurity_level\x18\x04 \x01(\x05R\rsecurityLevel2V\n" +
	"\tPqcEngine\x12I\n" +
	"\bEvaluate\x12\x1c.pqcengine.v1.ContextRequest\x1a\x1d.pqcengine.v1.AlgorithmConfig\"\x00B*Z(github.com/yourorg/janus/api/proto/v1;pbb\x06proto3"

var (
	file_api_proto_v1_policy_proto_rawDescOnce sync.Once
	file_api_proto_v1_policy_proto_rawDescData []byte
)

func file_api_proto_v1_policy_proto_rawDescGZIP() []byte {
	file_api_proto_v1_policy_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_policy_proto_rawDesc), len(file_api_proto_v1_policy_proto_rawDesc)))
	})
	return file_api_proto_v1_policy_proto_rawDescData
}

var file_api_proto_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_policy_proto_goTypes = []any{
	(*ContextRequest)(nil),  // 0: pqcengine.v1.ContextRequest
	(*AlgorithmConfig)(nil), // 1: pqcengine.v1.AlgorithmConfig
}
var file_api_proto_v1_policy_proto_depIdxs = []int32{
	0, // 0: pqcengine.v1.PqcEngine.Evaluate:input_type -> pqcengine.v1.ContextRequest
	1, // 1: pqcengine.v1.PqcEngine.Evaluate:output_type -> pqcengine.v1.AlgorithmConfig
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_policy_proto_init() }
func file_api_proto_v1_policy_proto_init() {
	if File_api_proto_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_policy_proto_rawDesc), len(file_api_proto_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_policy_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_policy_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_policy_proto_msgTypes,
	}.Build()
	File_api_proto_v1_policy_proto = out.File
	file_api_proto_v1_policy_proto_goTypes = nil
	file_api_proto_v1_policy_proto_depIdxs = nil
}
