// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/v1/policy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PqcEngine_Evaluate_FullMethodName = "/pqcengine.v1.PqcEngine/Evaluate"
)

// PqcEngineClient is the client API for PqcEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PqcEngineClient interface {
	Evaluate(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*AlgorithmConfig, error)
}

type pqcEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewPqcEngineClient(cc grpc.ClientConnInterface) PqcEngineClient {
	return &pqcEngineClient{cc}
}

func (c *pqcEngineClient) Evaluate(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*AlgorithmConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlgorithmConfig)
	err := c.cc.Invoke(ctx, PqcEngine_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PqcEngineServer is the server API for PqcEngine service.
// All implementations must embed UnimplementedPqcEngineServer
// for forward compatibility.
type PqcEngineServer interface {
	Evaluate(context.Context, *ContextRequest) (*AlgorithmConfig, error)
	mustEmbedUnimplementedPqcEngineServer()
}

// UnimplementedPqcEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPqcEngineServer struct{}

func (UnimplementedPqcEngineServer) Evaluate(context.Context, *ContextRequest) (*AlgorithmConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedPqcEngineServer) mustEmbedUnimplementedPqcEngineServer() {}
func (UnimplementedPqcEngineServer) testEmbeddedByValue()                   {}

// UnsafePqcEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PqcEngineServer will
// result in compilation errors.
type UnsafePqcEngineServer interface {
	mustEmbedUnimplementedPqcEngineServer()
}

func RegisterPqcEngineServer(s grpc.ServiceRegistrar, srv PqcEngineServer) {
	// If the following call panics, it indicates UnimplementedPqcEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PqcEngine_ServiceDesc, srv)
}

func _PqcEngine_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PqcEngineServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PqcEngine_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PqcEngineServer).Evaluate(ctx, req.(*ContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PqcEngine_ServiceDesc is the grpc.ServiceDesc for PqcEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PqcEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pqcengine.v1.PqcEngine",
	HandlerType: (*PqcEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _PqcEngine_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/policy.proto",
}
